### ISSUE TITLE
Help section / How_To.md is outdated and not yet translated to German

### ISSUE THREAD

**Issue by christophscheuing** [Aam-Digital/ndb-core#888] opened 2021-07-13 19:03 UTC
The How-To information shown in the "Help" section down left in the app is not up to date any more. It could be updated and then also be translated. Or we might think of another way of offering help to the users, e.g. just linking to a contact page.

**Comment by sleidig** [comment] 2021-07-20 15:59
duplicate of #836   This is a good point, however. I like your idea to include support contact details here instead. I'll take this up :+1:

**Closed by sleidig** 2021-07-20 15:59 UTC
Labels: Type: Documentation, discuss
