### ISSUE TITLE
Document Upload

### ISSUE THREAD

**Issue by TheSlimvReal** [Aam-Digital/ndb-core#780] opened 2021-04-20 15:51 UTC
*As a social woker I want to upload and download documents in Aam Digital in order to have all relevant information in one place.*
A common request is to upload documents for an individual child.
It might also be relevant to upload documents for schools, activities and notes in the future

**Proposed Solutions & Alternatives**
The documents should be uploaded to the Nextcloud, that is already connected with the application.
It should be possible to reference an array of documents with each entity (referenced by the entity id).
The upload and download of documents should be implemented as a dynamic component which can be used in the `EntityDetailsComponent`. This allows to also use this component for schools and activities.

**Comment by sleidig** [comment] 2021-04-20 15:54
duplicate of #89 . I am moving your (well written) description there and closing this

**Closed by sleidig** 2021-04-20 15:54 UTC
Labels: Priority: High, Status: Ready to Work On, Type: Feature
