### ISSUE TITLE
Extend display functionality of subentity record

### ISSUE THREAD

**Issue by Lorsbyjm** [Aam-Digital/ndb-core#219] opened 2019-01-17 19:55 UTC
The effect is only implemented in the child attendence section at the child details page. See #198 

- [ ] in smaller screens some columns are not displayed. Mobile users also should have the possibility to view all information.

To show these columns the properties could be shown in the elements row as key: value. Therefore the cells need to be extended. 
1. option: just extend the first cell and display all key:value pairs in a list underneath each other => hight of row increases.
2. option: extend all cells, Therefor you need to know which key:vlaue pair should be displayed
3. option: just a a line "For more information select row" and only display all information in a popup
4. option: rows as [expansion panels](https://material.angular.io/components/expansion/overview) that the user can click to show a version with much bigger height and all details

**Comment by sleidig** [comment] 2019-02-14 18:17
Isn't this being worked on in PR #198 and a duplicate of issue #197, @Lorsbyjm ?

**Comment by Lorsbyjm** [comment] 2019-02-14 19:45
It is a new feature. 
In PR 198 we just show some columns and some not. These values are only visible when selcting the row. 
@liwde idear was to show the disabled columns just as key value pair, so all properties of an entry are visible.

**Closed** 2021-07-04 15:34 UTC
Labels: Status: Ready to Work On, Type: Improvement, Type: UX
