### ISSUE TITLE
"Edit Data Structure" routes to 404 if user does not have route permissions

### ISSUE THREAD

**Issue by TheSlimvReal** [Aam-Digital/ndb-core#2166] opened 2024-01-09 10:22 UTC
**Describe the bug**
The "Edit Data Structure" button is shown whenever a user has `update` permissions on the `Config` entity. In some cases, especially when no permissions backend is used, all users have all permissions. 
Mostly the `/admin` route is still protected with a role guard which most users don't pass. 
This way the button is shown but when clicking it users land on the 404 route because they cannot access it.

Should the behaviour stay like this or should we also disable the button if the user does not have the required route permissions?

**Comment by sleidig** [comment] 2024-01-09 15:49
With the new AdminModule and UI there now is a hard-wired /admin sub-route that is managed by AdminModule itself and has all the related stuff under its hierarchy (e.g. /admin/site-settings , /admin/entity/..., etc.). To avoid the permissions bug you describe, the module itself doesn't have a role guard, but the subroutes have guards - some for entity action permissions, some for the admin_app role. (see [admin.routing.ts](https://github.com/Aam-Digital/ndb-core/blob/819285c54203281ed827ef148663c9cde807611b/src/app/core/admin/admin.routing.ts#L4)). I wanted to enable giving permissions for the data structures but not even more technical admin views by not always requiring admin_app.

If we stick to this (which I think will make maintenance easier, I had to copy around admin views for config again and again), the problem you describe will not occur in the future.
**But** we will have to "migrate" configs and remove all /admin views that are still defined in the config docs. And we probably should remove "update" permission on Config by default (if that is not already set to "read" normally).

Does that make sense and should we go ahead with the config cleanups? Or do you see other issues or approaches?

**Comment by TheSlimvReal** [comment] 2024-01-09 17:18
I understand what you mean. As far as I understand the migration would just mean kicking out any `/admin` routes from existing configs which should be fairly easy. 
There is only one drawback that for instances without permissions, we might not want show the "Edit Data Structure" to everyone. But we cannot assign a role to that route anymore if it is hardcoded. Alternatively we could still create a Permission object for this instances which would only give normal user the "read" permissions for the config (without actually enforcing it on the backend just for the UI aspects).

**Comment by sleidig** [comment] 2024-01-23 17:16
This is resolved with the discussed config migration. "view:admin" routes are removed from custom configs and the routing and permissions of the code-based AdminModule apply as intended.

**Closed by sleidig** 2024-01-23 17:16 UTC
Labels: Type: Bug
