### ISSUE TITLE
Cancelling to create a new note still adds it, no matter whether you say yes or no in confirmation

### ISSUE THREAD

**Issue by sleidig** [Aam-Digital/ndb-core#1258] opened 2022-05-06 14:35 UTC
**To Reproduce**
1. Go to notes list
2. Click on 'add new'
3. Give the note some title but then click "Cancel"

Bug A:
4. The app asks you whether you want to discard changes, say "Yes"
5. --> A new empty note is still added to the notes list nevertheless (would expect no new note to be saved)
Bug B:
4. repeat 1.-3. and then say "No" to discarding changes
5. --> A new empty note is added (but the title you gave it seems to be discarded)

**Comment by TheSlimvReal** [comment] 2022-05-11 07:12
The app asks you whether you want to **save** the changes.

Bug A: Cannot reproduce
Bug B: Will be fixed with #1261

**Closed** 2022-05-12 09:42 UTC
Labels: Type: Bug
