### ISSUE TITLE
Sync / Login loop 

### ISSUE THREAD

**Issue by fschoell** [Aam-Digital/ndb-core#70] opened 2017-07-06 20:11 UTC
The problem is when the user can be authenticated on the remote database but somehow not locally. 

I had this problem currently on the `entity_mapper` branch. The local login fails (username / password not correct because of the prefix change). However, due to the failed local login the `LoginComponent` get's stuck in a loop. First `onLoginFailure()` is called, which then calls `retryLoginAfterSync()`, which subscribes to the database sync status and then (because the sync actually works) will be notified about the completed sync, which then leads to another call to `login()`, which triggers another remote authentication and because this works (and the local authentication not), this triggers a new sync and the whole procedure from `onLoginFailure()`starts again.

**Comment by sleidig** [comment] 2017-07-07 03:50
Is this the same issue as #31 ?

**Comment by fschoell** [comment] 2017-07-10 19:22
Ok, found the bug. [This line](https://github.com/NGO-DB/ndb-core/blob/master/src/app/session/login/login.component.ts#L80) is actually the problem. It resets `isRetriedLogin` when `onLoginFailure()` is called. This is a problem, because this way [this statement](https://github.com/NGO-DB/ndb-core/blob/master/src/app/session/login/login.component.ts#L66) will always return true, no matter how many retries we actually had.

**Comment by Lorsbyjm** [comment] 2018-07-05 18:43
@liwde is this still possible?

**Comment by liwde** [comment] 2018-07-19 18:52
Recent changes (https://github.com/NGO-DB/ndb-core/pull/130) reintroduced this bug in the master.

fb7123d does work (all logging through AlertService)
d28c720 doesn't work (Merge PR130)

I'm investigating, but currently I don't see where the issue is coming from.

I tried to implement @fschoell's solution, but then the login didn't work at all. 
I also tried to always `self.retryLoginSubscription.unsubscribe();` regardless of sync state (sync works fine, as described above), but then Login doesn't work at all.

I will continue investigating next week.

**Comment by sleidig** [comment] 2018-07-23 10:02
So this is only occurring when the remote login succeeds and the local login fails? That would be a fringe case that only occurs on an inconsistent database, isn't it?
I'd suggest to first finish the redesign of the whole Session/Login system (#78) and only then look back at this to see whether it still occurs.

**Comment by sleidig** [comment] 2019-11-30 18:04
closing this as the whole session/login architecture has changed with PR #246 (issue #78). If similar problems come up again we can open a new issue.

**Closed by sleidig** 2019-11-30 18:04 UTC
Labels: Status: Blocked, Type: Bug
