### ISSUE TITLE
More configurable wording

### ISSUE THREAD

**Issue by TheSlimvReal** [Aam-Digital/ndb-core#1454] opened 2022-09-22 16:22 UTC
In some places of the application the wording is still quite hard-coded.
For example some dashboard widgets use the term `cases`. While this term is very broad, not all the organisation can identify with it. As this term is used in multiple locations, it would be useful to have it also configurable. 

A quick and easy solution would be to re-use the name that is used in the list or details view of that entity.

An alternative approach would be to add this to the entity configuration. 
This could look somethings like the following:
```json
"entity:Child": {
   "labels": {
       "singular": "Student",
       "plural": "Students"
   }
}
```
and then it could be used directly from the entity:
```javascript
const label = Child.getSingularLabel()
```

The scope of this issue should be to find a solution for this general wording issues (e.g. one of the described approaches) as well as updating the app to correctly use this new solution everywhere.

**Comment by sleidig** [comment] 2022-10-03 07:41
I think this is a duplicate of #886 ?

**Closed** 2022-10-04 08:03 UTC
Labels: Type: UX
